from tkinter import *
from PIL import ImageTk,Image
from tkinter import ttk
from tkinter import messagebox
import mysql.connector
import random
from time import strftime
from datetime import date, datetime
from ceneInabavka import CeneNabavka
from veza import Konekcija

class Restoran:
    def __init__(self,root):
        self.root=root
        self.root.title("Restoran")
        self.root.geometry("1850x1050+0+0")

        self.root.protocol('WM_DELETE_WINDOW',self.zatvoriProzor)

        self.var_količina1=IntVar()
        self.var_količina2=IntVar()
        self.var_količina3=IntVar()
        self.var_količina4=IntVar()
        self.var_količina5=IntVar()
        self.var_količina6=IntVar()
        self.var_količina7=IntVar()
        self.var_količina8=IntVar()
        self.var_količina9=IntVar()
        self.var_količina10=IntVar()
        self.var_količina11=IntVar()
        self.var_količina12=IntVar()
        self.var_količina13=IntVar()
        self.var_količina14=IntVar()
        self.var_količina15=IntVar()
        self.var_količina16=IntVar()
        self.var_količina17=IntVar()
        self.var_količina18=IntVar()
        self.var_količina19=IntVar()
        self.var_količina20=IntVar()
        self.var_količina21=IntVar()
        self.var_količina22=IntVar()
        self.var_količina23=IntVar()
        self.var_količina24=IntVar()
        self.var_količina25=IntVar()
        self.var_količina26=IntVar()
        self.var_espresso=StringVar()
        self.var_espresso.set("Espresso")
        self.var_aqua=StringVar()
        self.var_aqua.set("Aqua Viva")
        self.var_knjaz=StringVar()
        self.var_knjaz.set("Knjaz Miloš")
        self.var_coca=StringVar()
        self.var_coca.set("Coca Cola")
        self.var_next=StringVar()
        self.var_next.set("Next")
        self.var_limunada=StringVar()
        self.var_limunada.set("Limunada")
        self.var_cedjena=StringVar()
        self.var_cedjena.set("Cedjena Narandža")
        self.var_redbull=StringVar()
        self.var_redbull.set("Red Bull")
        self.var_kozel=StringVar()
        self.var_kozel.set("Kozel")
        self.var_vino=StringVar()
        self.var_vino.set("Crveno Vino")
        self.var_whisky=StringVar()
        self.var_whisky.set("Whisky")
        self.var_cognac=StringVar()
        self.var_cognac.set("Cognac")
        self.var_martini=StringVar()
        self.var_martini.set("Martini")
        self.var_omlet=StringVar()
        self.var_omlet.set("Omlet")
        self.var_pomfrit=StringVar()
        self.var_pomfrit.set("Pomfrit")
        self.var_meze=StringVar()
        self.var_meze.set("Meze")
        self.var_sendvič=StringVar()
        self.var_sendvič.set("Klub Sendvič")
        self.var_čorba=StringVar()
        self.var_čorba.set("Teleća Čorba")
        self.var_paradajz=StringVar()
        self.var_paradajz.set("Paradajz Salata")
        self.var_krastavac=StringVar()
        self.var_krastavac.set("Krastavac Svež")
        self.var_pečurke=StringVar()
        self.var_pečurke.set("Pečurke na žaru")
        self.var_špagete=StringVar()
        self.var_špagete.set("Špagete")
        self.var_bečka=StringVar()
        self.var_bečka.set("Bečka Šnicla")
        self.var_medaljoni=StringVar()
        self.var_medaljoni.set("Svinjski Medaljoni")
        self.var_pastrmka=StringVar()
        self.var_pastrmka.set("Sveža Pastrmka")
        self.var_tuna=StringVar()
        self.var_tuna.set("Tuna")
        self.var_cena1=IntVar()
        self.var_cena2=IntVar()
        self.var_cena3=IntVar()
        self.var_cena4=IntVar()
        self.var_cena5=IntVar()
        self.var_cena6=IntVar()
        self.var_cena7=IntVar()
        self.var_cena8=IntVar()
        self.var_cena9=IntVar()
        self.var_cena10=IntVar()
        self.var_cena11=IntVar()
        self.var_cena12=IntVar()
        self.var_cena13=IntVar()
        self.var_cena14=IntVar()
        self.var_cena15=IntVar()
        self.var_cena16=IntVar()
        self.var_cena17=IntVar()
        self.var_cena18=IntVar()
        self.var_cena19=IntVar()
        self.var_cena20=IntVar()
        self.var_cena21=IntVar()
        self.var_cena22=IntVar()
        self.var_cena23=IntVar()
        self.var_cena24=IntVar()
        self.var_cena25=IntVar()
        self.var_cena26=IntVar()
        self.var_idA1=IntVar()
        self.var_idA2=IntVar()
        self.var_idA3=IntVar()
        self.var_idA4=IntVar()
        self.var_idA5=IntVar()
        self.var_idA6=IntVar()
        self.var_idA7=IntVar()
        self.var_idA8=IntVar()
        self.var_idA9=IntVar()
        self.var_idA10=IntVar()
        self.var_idA11=IntVar()
        self.var_idA12=IntVar()
        self.var_idA13=IntVar()
        self.var_idA14=IntVar()
        self.var_idA15=IntVar()
        self.var_idA16=IntVar()
        self.var_idA17=IntVar()
        self.var_idA18=IntVar()
        self.var_idA19=IntVar()
        self.var_idA20=IntVar()
        self.var_idA21=IntVar()
        self.var_idA22=IntVar()
        self.var_idA23=IntVar()
        self.var_idA24=IntVar()
        self.var_idA25=IntVar()
        self.var_idA26=IntVar()
        self.var_KN1=IntVar()
        self.var_KN2=IntVar()
        self.var_KN3=IntVar()
        self.var_KN4=IntVar()
        self.var_KN5=IntVar()
        self.var_KN6=IntVar()
        self.var_KN7=IntVar()
        self.var_KN8=IntVar()
        self.var_KN9=IntVar()
        self.var_KN10=IntVar()
        self.var_KN11=IntVar()
        self.var_KN12=IntVar()
        self.var_KN13=IntVar()
        self.var_KN14=IntVar()
        self.var_KN15=IntVar()
        self.var_KN16=IntVar()
        self.var_KN17=IntVar()
        self.var_KN18=IntVar()
        self.var_KN19=IntVar()
        self.var_KN20=IntVar()
        self.var_KN21=IntVar()
        self.var_KN22=IntVar()
        self.var_KN23=IntVar()
        self.var_KN24=IntVar()
        self.var_KN25=IntVar()
        self.var_KN26=IntVar()

        self.var_pronadjiPo=StringVar()
        self.var_pronadjiTekst=StringVar()

        self.var_brojračuna=IntVar()
        self.var_idgosti=IntVar()
        self.var_stanje=IntVar()
        self.var_total=IntVar()
        self.var_statusR=StringVar()
        self.var_statusR.set("otvoren")
        self.var_računDan=IntVar()

        self.var_dan=IntVar()
        self.var_pazar=IntVar()
        self.var_statusD=StringVar()
        

        self.var_idnormativa=IntVar()
        self.var_nazivArtikla=StringVar()
        self.var_cenaArtikla=IntVar()
        self.var_količinaArtikla=IntVar()
        self.var_idartikla=IntVar()

        self.var_tura=IntVar()


        img1=Image.open(r"restoraniFoto/restoran5.jpg")
        img1=img1.resize((620,140),Image.ANTIALIAS)
        self.photoimg1=ImageTk.PhotoImage(img1)

        lblImage=Label(self.root,image=self.photoimg1,bd=4,relief=RIDGE)
        lblImage.place(x=0,y=0,width=620,height=140)

        img2=Image.open(r"restoraniFoto/restoran2.jpg")
        img2=img2.resize((620,140),Image.ANTIALIAS)
        self.photoimg2=ImageTk.PhotoImage(img2)

        lblImage2=Label(self.root,image=self.photoimg2,bd=4,relief=RIDGE)
        lblImage2.place(x=620,y=0,width=620,height=140)

        img3=Image.open(r"restoraniFoto/restoran1.jpg")
        img3=img3.resize((610,140),Image.ANTIALIAS)
        self.photoimg3=ImageTk.PhotoImage(img3)

        lblImage3=Label(self.root,image=self.photoimg3,bd=4,relief=RIDGE)
        lblImage3.place(x=1240,y=0,width=610,height=140)

        titleLbl=Label(self.root,text="Restoran sistem i naplata",font=("times new roman",40,"bold"),bg="black",fg="gold",bd=4,relief=RIDGE)
        titleLbl.place(x=0,y=140,width=1850,height=70)

        self.lbl = Label(self.root, font = ('calibri', 15, 'bold'),
        foreground = 'gold',background="black")
        self.lbl.place(x=10,y=160,width=300)
        self.datum()


        frameArtikli=Frame(self.root,bg="black",bd=4,relief=RIDGE)
        frameArtikli.place(x=0,y=210,width=920,height=800)

        img4=Image.open(r"pićeFoto/espresso.jpg")
        img4=img4.resize((100,50),Image.ANTIALIAS)
        self.photoimg4=ImageTk.PhotoImage(img4)
        l1=Label(frameArtikli,image=self.photoimg4)
        l1.place(x=10,y=10,width=100,height=50)
        upis1=ttk.Entry(frameArtikli,textvariable=self.var_količina1)
        upis1.place(x=120,y=30,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_espresso)
        upisC.place(x=180,y=30,width=100,height=30)
        Upis1=ttk.Entry(frameArtikli,textvariable=self.var_cena1)
        Upis1.place(x=290,y=30,width=70,height=30)
        id1=ttk.Entry(frameArtikli,textvariable=self.var_idA1)
        id1.place(x=370,y=30,width=30,height=30)
        kN1=ttk.Entry(frameArtikli,textvariable=self.var_KN1)
        kN1.place(x=390,y=30,width=50,height=30)

        img5=Image.open(r"pićeFoto/aqua viva.jpg")
        img5=img5.resize((100,50),Image.ANTIALIAS)
        self.photoimg5=ImageTk.PhotoImage(img5)
        l2=Label(frameArtikli,image=self.photoimg5)
        l2.place(x=10,y=70,width=100,height=50)
        upis2=ttk.Entry(frameArtikli,textvariable=self.var_količina2)
        upis2.place(x=120,y=90,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_aqua)
        upisR.place(x=180,y=90,width=100,height=30)
        Upis2=ttk.Entry(frameArtikli,textvariable=self.var_cena2)
        Upis2.place(x=290,y=90,width=70,height=30)
        id2=ttk.Entry(frameArtikli,textvariable=self.var_idA2)
        id2.place(x=370,y=90,width=30,height=30)
        kN2=ttk.Entry(frameArtikli,textvariable=self.var_KN2)
        kN2.place(x=390,y=90,width=50,height=30)

        img6=Image.open(r"pićeFoto/knjaz.jpg")
        img6=img6.resize((100,50),Image.ANTIALIAS)
        self.photoimg6=ImageTk.PhotoImage(img6)
        l3=Label(frameArtikli,image=self.photoimg6)
        l3.place(x=10,y=130,width=100,height=50)
        upis3=ttk.Entry(frameArtikli,textvariable=self.var_količina3)
        upis3.place(x=120,y=150,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_knjaz)
        upisK.place(x=180,y=150,width=100,height=30)
        Upis3=ttk.Entry(frameArtikli,textvariable=self.var_cena3)
        Upis3.place(x=290,y=150,width=70,height=30)
        id3=ttk.Entry(frameArtikli,textvariable=self.var_idA3)
        id3.place(x=370,y=150,width=30,height=30)
        kN3=ttk.Entry(frameArtikli,textvariable=self.var_KN3)
        kN3.place(x=390,y=150,width=50,height=30)

        img7=Image.open(r"pićeFoto/coke.png")
        img7=img7.resize((100,50),Image.ANTIALIAS)
        self.photoimg7=ImageTk.PhotoImage(img7)
        l4=Label(frameArtikli,image=self.photoimg7)
        l4.place(x=10,y=190,width=100,height=50)
        upis4=ttk.Entry(frameArtikli,textvariable=self.var_količina4)
        upis4.place(x=120,y=210,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_coca)
        upisC.place(x=180,y=210,width=100,height=30)
        Upis4=ttk.Entry(frameArtikli,textvariable=self.var_cena4)
        Upis4.place(x=290,y=210,width=70,height=30)
        id4=ttk.Entry(frameArtikli,textvariable=self.var_idA4)
        id4.place(x=370,y=210,width=30,height=30)
        kN4=ttk.Entry(frameArtikli,textvariable=self.var_KN4)
        kN4.place(x=390,y=210,width=50,height=30)

        img8=Image.open(r"pićeFoto/next.jpg")
        img8=img8.resize((100,50),Image.ANTIALIAS)
        self.photoimg8=ImageTk.PhotoImage(img8)
        l5=Label(frameArtikli,image=self.photoimg8)
        l5.place(x=10,y=250,width=100,height=50)
        upis5=ttk.Entry(frameArtikli,textvariable=self.var_količina5)
        upis5.place(x=120,y=270,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_next)
        upisR.place(x=180,y=270,width=100,height=30)
        Upis5=ttk.Entry(frameArtikli,textvariable=self.var_cena5)
        Upis5.place(x=290,y=270,width=70,height=30)
        id5=ttk.Entry(frameArtikli,textvariable=self.var_idA5)
        id5.place(x=370,y=270,width=30,height=30)
        kN5=ttk.Entry(frameArtikli,textvariable=self.var_KN5)
        kN5.place(x=390,y=270,width=50,height=30)

        img9=Image.open(r"pićeFoto/limunada.jpg")
        img9=img9.resize((100,50),Image.ANTIALIAS)
        self.photoimg9=ImageTk.PhotoImage(img9)
        l6=Label(frameArtikli,image=self.photoimg9)
        l6.place(x=10,y=310,width=100,height=50)
        upis6=ttk.Entry(frameArtikli,textvariable=self.var_količina6)
        upis6.place(x=120,y=330,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_limunada)
        upisK.place(x=180,y=330,width=100,height=30)
        Upis6=ttk.Entry(frameArtikli,textvariable=self.var_cena6)
        Upis6.place(x=290,y=330,width=70,height=30)
        id6=ttk.Entry(frameArtikli,textvariable=self.var_idA6)
        id6.place(x=370,y=330,width=30,height=30)
        kN6=ttk.Entry(frameArtikli,textvariable=self.var_KN6)
        kN6.place(x=390,y=330,width=50,height=30)

        img10=Image.open(r"pićeFoto/cedjena.jpeg")
        img10=img10.resize((100,50),Image.ANTIALIAS)
        self.photoimg10=ImageTk.PhotoImage(img10)
        l7=Label(frameArtikli,image=self.photoimg10)
        l7.place(x=10,y=370,width=100,height=50)
        upis7=ttk.Entry(frameArtikli,textvariable=self.var_količina7)
        upis7.place(x=120,y=390,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_cedjena)
        upisC.place(x=180,y=390,width=100,height=30)
        Upis7=ttk.Entry(frameArtikli,textvariable=self.var_cena7)
        Upis7.place(x=290,y=390,width=70,height=30)
        id7=ttk.Entry(frameArtikli,textvariable=self.var_idA7)
        id7.place(x=370,y=390,width=30,height=30)
        kN7=ttk.Entry(frameArtikli,textvariable=self.var_KN7)
        kN7.place(x=390,y=390,width=50,height=30)

        img11=Image.open(r"pićeFoto/redbull.jpg")
        img11=img11.resize((100,50),Image.ANTIALIAS)
        self.photoimg11=ImageTk.PhotoImage(img11)
        l8=Label(frameArtikli,image=self.photoimg11)
        l8.place(x=10,y=430,width=100,height=50)
        upis8=ttk.Entry(frameArtikli,textvariable=self.var_količina8)
        upis8.place(x=120,y=450,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_redbull)
        upisR.place(x=180,y=450,width=100,height=30)
        Upis8=ttk.Entry(frameArtikli,textvariable=self.var_cena8)
        Upis8.place(x=290,y=450,width=70,height=30)
        id8=ttk.Entry(frameArtikli,textvariable=self.var_idA8)
        id8.place(x=370,y=450,width=30,height=30)
        kN8=ttk.Entry(frameArtikli,textvariable=self.var_KN8)
        kN8.place(x=390,y=450,width=50,height=30)

        img12=Image.open(r"pićeFoto/kozel.png")
        img12=img12.resize((100,50),Image.ANTIALIAS)
        self.photoimg12=ImageTk.PhotoImage(img12)
        l9=Label(frameArtikli,image=self.photoimg12)
        l9.place(x=10,y=490,width=100,height=50)
        upis9=ttk.Entry(frameArtikli,textvariable=self.var_količina9)
        upis9.place(x=120,y=510,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_kozel)
        upisK.place(x=180,y=510,width=100,height=30)
        Upis9=ttk.Entry(frameArtikli,textvariable=self.var_cena9)
        Upis9.place(x=290,y=510,width=70,height=30)
        id9=ttk.Entry(frameArtikli,textvariable=self.var_idA9)
        id9.place(x=370,y=510,width=30,height=30)
        kN9=ttk.Entry(frameArtikli,textvariable=self.var_KN9)
        kN9.place(x=390,y=510,width=50,height=30)

        img13=Image.open(r"pićeFoto/vino.png")
        img13=img13.resize((100,50),Image.ANTIALIAS)
        self.photoimg13=ImageTk.PhotoImage(img13)
        l10=Label(frameArtikli,image=self.photoimg13)
        l10.place(x=10,y=550,width=100,height=50)
        upis10=ttk.Entry(frameArtikli,textvariable=self.var_količina10)
        upis10.place(x=120,y=570,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_vino)
        upisC.place(x=180,y=570,width=100,height=30)
        Upis10=ttk.Entry(frameArtikli,textvariable=self.var_cena10)
        Upis10.place(x=290,y=570,width=70,height=30)
        id10=ttk.Entry(frameArtikli,textvariable=self.var_idA10)
        id10.place(x=370,y=570,width=30,height=30)
        kN10=ttk.Entry(frameArtikli,textvariable=self.var_KN10)
        kN10.place(x=390,y=570,width=50,height=30)

        img14=Image.open(r"pićeFoto/whisky.jpg")
        img14=img14.resize((100,50),Image.ANTIALIAS)
        self.photoimg14=ImageTk.PhotoImage(img14)
        l11=Label(frameArtikli,image=self.photoimg14)
        l11.place(x=10,y=610,width=100,height=50)
        upis11=ttk.Entry(frameArtikli,textvariable=self.var_količina11)
        upis11.place(x=120,y=630,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_whisky)
        upisR.place(x=180,y=630,width=100,height=30)
        Upis11=ttk.Entry(frameArtikli,textvariable=self.var_cena11)
        Upis11.place(x=290,y=630,width=70,height=30)
        id11=ttk.Entry(frameArtikli,textvariable=self.var_idA11)
        id11.place(x=370,y=630,width=30,height=30)
        kN11=ttk.Entry(frameArtikli,textvariable=self.var_KN11)
        kN11.place(x=390,y=630,width=50,height=30)

        img15=Image.open(r"pićeFoto/cognac.jpg")
        img15=img15.resize((100,50),Image.ANTIALIAS)
        self.photoimg15=ImageTk.PhotoImage(img15)
        l12=Label(frameArtikli,image=self.photoimg15)
        l12.place(x=10,y=670,width=100,height=50)
        upis12=ttk.Entry(frameArtikli,textvariable=self.var_količina12)
        upis12.place(x=120,y=690,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_cognac)
        upisK.place(x=180,y=690,width=100,height=30)
        Upis12=ttk.Entry(frameArtikli,textvariable=self.var_cena12)
        Upis12.place(x=290,y=690,width=70,height=30)
        id12=ttk.Entry(frameArtikli,textvariable=self.var_idA12)
        id12.place(x=370,y=690,width=30,height=30)
        kN12=ttk.Entry(frameArtikli,textvariable=self.var_KN12)
        kN12.place(x=390,y=690,width=50,height=30)

        img16=Image.open(r"pićeFoto/martini.jpeg")
        img16=img16.resize((100,50),Image.ANTIALIAS)
        self.photoimg16=ImageTk.PhotoImage(img16)
        l13=Label(frameArtikli,image=self.photoimg16)
        l13.place(x=10,y=730,width=100,height=50)
        upis13=ttk.Entry(frameArtikli,textvariable=self.var_količina13)
        upis13.place(x=120,y=750,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_martini)
        upisK.place(x=180,y=750,width=100,height=30)
        Upis13=ttk.Entry(frameArtikli,textvariable=self.var_cena13)
        Upis13.place(x=290,y=750,width=70,height=30)
        id13=ttk.Entry(frameArtikli,textvariable=self.var_idA13)
        id13.place(x=370,y=750,width=30,height=30)
        kN13=ttk.Entry(frameArtikli,textvariable=self.var_KN13)
        kN13.place(x=390,y=750,width=50,height=30)

### novi red

        img17=Image.open(r"hranaFoto/omlet.jpg")
        img17=img17.resize((100,50),Image.ANTIALIAS)
        self.photoimg17=ImageTk.PhotoImage(img17)
        l14=Label(frameArtikli,image=self.photoimg17)
        l14.place(x=460,y=10,width=100,height=50)
        upis14=ttk.Entry(frameArtikli,textvariable=self.var_količina14)
        upis14.place(x=570,y=30,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_omlet)
        upisC.place(x=630,y=30,width=100,height=30)
        Upis14=ttk.Entry(frameArtikli,textvariable=self.var_cena14)
        Upis14.place(x=740,y=30,width=70,height=30)
        id14=ttk.Entry(frameArtikli,textvariable=self.var_idA14)
        id14.place(x=820,y=30,width=30,height=30)
        kN14=ttk.Entry(frameArtikli,textvariable=self.var_KN14)
        kN14.place(x=840,y=30,width=50,height=30)

        img18=Image.open(r"hranaFoto/pomfrit.jpg")
        img18=img18.resize((100,50),Image.ANTIALIAS)
        self.photoimg18=ImageTk.PhotoImage(img18)
        l15=Label(frameArtikli,image=self.photoimg18)
        l15.place(x=460,y=70,width=100,height=50)
        upis15=ttk.Entry(frameArtikli,textvariable=self.var_količina15)
        upis15.place(x=570,y=90,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_pomfrit)
        upisR.place(x=630,y=90,width=100,height=30)
        Upis15=ttk.Entry(frameArtikli,textvariable=self.var_cena15)
        Upis15.place(x=740,y=90,width=70,height=30)
        id15=ttk.Entry(frameArtikli,textvariable=self.var_idA15)
        id15.place(x=820,y=90,width=30,height=30)
        kN15=ttk.Entry(frameArtikli,textvariable=self.var_KN15)
        kN15.place(x=840,y=90,width=50,height=30)

        img19=Image.open(r"hranaFoto/meze.jpg")
        img19=img19.resize((100,50),Image.ANTIALIAS)
        self.photoimg19=ImageTk.PhotoImage(img19)
        l16=Label(frameArtikli,image=self.photoimg19)
        l16.place(x=460,y=130,width=100,height=50)
        upis16=ttk.Entry(frameArtikli,textvariable=self.var_količina16)
        upis16.place(x=570,y=150,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_meze)
        upisK.place(x=630,y=150,width=100,height=30)
        Upis16=ttk.Entry(frameArtikli,textvariable=self.var_cena16)
        Upis16.place(x=740,y=150,width=70,height=30)
        id16=ttk.Entry(frameArtikli,textvariable=self.var_idA16)
        id16.place(x=820,y=150,width=30,height=30)
        kN16=ttk.Entry(frameArtikli,textvariable=self.var_KN16)
        kN16.place(x=840,y=150,width=50,height=30)

        img20=Image.open(r"hranaFoto/klubsendvič.jpg")
        img20=img20.resize((100,50),Image.ANTIALIAS)
        self.photoimg20=ImageTk.PhotoImage(img20)
        l17=Label(frameArtikli,image=self.photoimg20)
        l17.place(x=460,y=190,width=100,height=50)
        upis17=ttk.Entry(frameArtikli,textvariable=self.var_količina17)
        upis17.place(x=570,y=210,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_sendvič)
        upisC.place(x=630,y=210,width=100,height=30)
        Upis17=ttk.Entry(frameArtikli,textvariable=self.var_cena17)
        Upis17.place(x=740,y=210,width=70,height=30)
        id17=ttk.Entry(frameArtikli,textvariable=self.var_idA17)
        id17.place(x=820,y=210,width=30,height=30)
        kN17=ttk.Entry(frameArtikli,textvariable=self.var_KN17)
        kN17.place(x=840,y=210,width=50,height=30)

        img21=Image.open(r"hranaFoto/čorba.jpg")
        img21=img21.resize((100,50),Image.ANTIALIAS)
        self.photoimg21=ImageTk.PhotoImage(img21)
        l18=Label(frameArtikli,image=self.photoimg21)
        l18.place(x=460,y=250,width=100,height=50)
        upis18=ttk.Entry(frameArtikli,textvariable=self.var_količina18)
        upis18.place(x=570,y=270,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_čorba)
        upisR.place(x=630,y=270,width=100,height=30)
        Upis18=ttk.Entry(frameArtikli,textvariable=self.var_cena18)
        Upis18.place(x=740,y=270,width=70,height=30)
        id18=ttk.Entry(frameArtikli,textvariable=self.var_idA18)
        id18.place(x=820,y=270,width=70,height=30)
        kN18=ttk.Entry(frameArtikli,textvariable=self.var_KN18)
        kN18.place(x=840,y=270,width=50,height=30)

        img22=Image.open(r"hranaFoto/paradajz.jpg")
        img22=img22.resize((100,50),Image.ANTIALIAS)
        self.photoimg22=ImageTk.PhotoImage(img22)
        l19=Label(frameArtikli,image=self.photoimg22)
        l19.place(x=460,y=310,width=100,height=50)
        upis19=ttk.Entry(frameArtikli,textvariable=self.var_količina19)
        upis19.place(x=570,y=330,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_paradajz)
        upisK.place(x=630,y=330,width=100,height=30)
        Upis19=ttk.Entry(frameArtikli,textvariable=self.var_cena19)
        Upis19.place(x=740,y=330,width=70,height=30)
        id19=ttk.Entry(frameArtikli,textvariable=self.var_idA19)
        id19.place(x=820,y=330,width=30,height=30)
        kN19=ttk.Entry(frameArtikli,textvariable=self.var_KN19)
        kN19.place(x=840,y=330,width=50,height=30)

        img23=Image.open(r"hranaFoto/krastavac.jpg")
        img23=img23.resize((100,50),Image.ANTIALIAS)
        self.photoimg23=ImageTk.PhotoImage(img23)
        l20=Label(frameArtikli,image=self.photoimg23)
        l20.place(x=460,y=370,width=100,height=50)
        upis20=ttk.Entry(frameArtikli,textvariable=self.var_količina20)
        upis20.place(x=570,y=390,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_krastavac)
        upisC.place(x=630,y=390,width=100,height=30)
        Upis20=ttk.Entry(frameArtikli,textvariable=self.var_cena20)
        Upis20.place(x=740,y=390,width=70,height=30)
        id20=ttk.Entry(frameArtikli,textvariable=self.var_idA20)
        id20.place(x=820,y=390,width=30,height=30)
        kN20=ttk.Entry(frameArtikli,textvariable=self.var_KN20)
        kN20.place(x=840,y=390,width=50,height=30)

        img24=Image.open(r"hranaFoto/pečurke.png")
        img24=img24.resize((100,50),Image.ANTIALIAS)
        self.photoimg24=ImageTk.PhotoImage(img24)
        l21=Label(frameArtikli,image=self.photoimg24)
        l21.place(x=460,y=430,width=100,height=50)
        upis21=ttk.Entry(frameArtikli,textvariable=self.var_količina21)
        upis21.place(x=570,y=450,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_pečurke)
        upisR.place(x=630,y=450,width=100,height=30)
        Upis21=ttk.Entry(frameArtikli,textvariable=self.var_cena21)
        Upis21.place(x=740,y=450,width=70,height=30)
        id21=ttk.Entry(frameArtikli,textvariable=self.var_idA21)
        id21.place(x=820,y=450,width=30,height=30)
        kN21=ttk.Entry(frameArtikli,textvariable=self.var_KN21)
        kN21.place(x=840,y=450,width=50,height=30)

        img25=Image.open(r"hranaFoto/špagete.jpg")
        img25=img25.resize((100,50),Image.ANTIALIAS)
        self.photoimg25=ImageTk.PhotoImage(img25)
        l22=Label(frameArtikli,image=self.photoimg25)
        l22.place(x=460,y=490,width=100,height=50)
        upis22=ttk.Entry(frameArtikli,textvariable=self.var_količina22)
        upis22.place(x=570,y=510,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_špagete)
        upisK.place(x=630,y=510,width=100,height=30)
        upis22=ttk.Entry(frameArtikli,textvariable=self.var_cena22)
        upis22.place(x=740,y=510,width=70,height=30)
        id22=ttk.Entry(frameArtikli,textvariable=self.var_idA22)
        id22.place(x=820,y=510,width=30,height=30)
        kN22=ttk.Entry(frameArtikli,textvariable=self.var_KN22)
        kN22.place(x=840,y=510,width=50,height=30)

        img26=Image.open(r"hranaFoto/bečka.jpeg")
        img26=img26.resize((100,50),Image.ANTIALIAS)
        self.photoimg26=ImageTk.PhotoImage(img26)
        l23=Label(frameArtikli,image=self.photoimg26)
        l23.place(x=460,y=550,width=100,height=50)
        upis23=ttk.Entry(frameArtikli,textvariable=self.var_količina23)
        upis23.place(x=570,y=570,width=50,height=30)
        upisC=ttk.Entry(frameArtikli,textvariable=self.var_bečka)
        upisC.place(x=630,y=570,width=100,height=30)
        Upis23=ttk.Entry(frameArtikli,textvariable=self.var_cena23)
        Upis23.place(x=740,y=570,width=70,height=30)
        id23=ttk.Entry(frameArtikli,textvariable=self.var_idA23)
        id23.place(x=820,y=570,width=30,height=30)
        kN23=ttk.Entry(frameArtikli,textvariable=self.var_KN23)
        kN23.place(x=840,y=570,width=50,height=30)

        img27=Image.open(r"hranaFoto/file.jpg")
        img27=img27.resize((100,50),Image.ANTIALIAS)
        self.photoimg27=ImageTk.PhotoImage(img27)
        l24=Label(frameArtikli,image=self.photoimg27)
        l24.place(x=460,y=610,width=100,height=50)
        upis24=ttk.Entry(frameArtikli,textvariable=self.var_količina24)
        upis24.place(x=570,y=630,width=50,height=30)
        upisR=ttk.Entry(frameArtikli,textvariable=self.var_medaljoni)
        upisR.place(x=630,y=630,width=100,height=30)
        Upis24=ttk.Entry(frameArtikli,textvariable=self.var_cena24)
        Upis24.place(x=740,y=630,width=70,height=30)
        id24=ttk.Entry(frameArtikli,textvariable=self.var_idA24)
        id24.place(x=820,y=630,width=30,height=30)
        kN24=ttk.Entry(frameArtikli,textvariable=self.var_KN24)
        kN24.place(x=840,y=630,width=50,height=30)

        img28=Image.open(r"hranaFoto/pastrmka.jpg")
        img28=img28.resize((100,50),Image.ANTIALIAS)
        self.photoimg28=ImageTk.PhotoImage(img28)
        l25=Label(frameArtikli,image=self.photoimg28)
        l25.place(x=460,y=670,width=100,height=50)
        upis25=ttk.Entry(frameArtikli,textvariable=self.var_količina25)
        upis25.place(x=570,y=690,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_pastrmka)
        upisK.place(x=630,y=690,width=100,height=30)
        Upis25=ttk.Entry(frameArtikli,textvariable=self.var_cena25)
        Upis25.place(x=740,y=690,width=70,height=30)
        id25=ttk.Entry(frameArtikli,textvariable=self.var_idA25)
        id25.place(x=820,y=690,width=30,height=30)
        k25=ttk.Entry(frameArtikli,textvariable=self.var_KN25)
        k25.place(x=840,y=690,width=50,height=30)

        img29=Image.open(r"hranaFoto/tuna.jpg")
        img29=img29.resize((100,50),Image.ANTIALIAS)
        self.photoimg29=ImageTk.PhotoImage(img29)
        l26=Label(frameArtikli,image=self.photoimg29)
        l26.place(x=460,y=730,width=100,height=50)
        upis26=ttk.Entry(frameArtikli,textvariable=self.var_količina26)
        upis26.place(x=570,y=750,width=50,height=30)
        upisK=ttk.Entry(frameArtikli,textvariable=self.var_tuna)
        upisK.place(x=630,y=750,width=100,height=30)
        Upis26=ttk.Entry(frameArtikli,textvariable=self.var_cena26)
        Upis26.place(x=740,y=750,width=70,height=30)
        id26=ttk.Entry(frameArtikli,textvariable=self.var_idA26)
        id26.place(x=820,y=750,width=30,height=30)
        kN26=ttk.Entry(frameArtikli,textvariable=self.var_KN26)
        kN26.place(x=840,y=750,width=50,height=30)


        frameRačuni=LabelFrame(self.root,bd=2,relief=RIDGE,text="Pogledaj detalje i pretraži račune",font=("times new roman",12,"bold"),padx=2)
        frameRačuni.place(x=930,y=210,width=540,height=300)

        pronadjiCombo=ttk.Combobox(frameRačuni,textvariable=self.var_pronadjiPo,font=("times new roman",12,"bold"),width=14,state="readonly")
        pronadjiCombo['value']=("brojračuna","status")
        pronadjiCombo.current()
        pronadjiCombo.grid(row=0,column=1,padx=2)
   
        pronadjiTekst=ttk.Entry(frameRačuni,textvariable=self.var_pronadjiTekst, font=("times new roman",12,"bold"),width=14)
        pronadjiTekst.grid(row=0,column=2,padx=2)

        btnPronadji=Button(frameRačuni,text="Pronadji",command=self.pronadjiračun, font=("times new roman",12,"bold"),bg="black",fg="gold",width=7)
        btnPronadji.grid(row=0,column=3,padx=1)

        btnPrikaži=Button(frameRačuni,text="Prikaži Sve",command=self.prikažiSveRačune, font=("times new roman",12,"bold"),bg="black",fg="gold",width=7)
        btnPrikaži.grid(row=0,column=4,padx=1)

        detaljiTabla1 =Frame(frameRačuni,bg="purple")
        detaljiTabla1.place(x=0,y=50,width=530,height=230)

        scroll_x = Scrollbar(detaljiTabla1,orient=HORIZONTAL)
        scroll_y = Scrollbar(detaljiTabla1,orient=VERTICAL)
        self.ispis=ttk.Treeview(detaljiTabla1,columns=("brojračuna","idgosti","trenutnostanje","total","status","računDan"),xscrollcommand=scroll_x.set,yscrollcommand=scroll_y.set)
        scroll_x.pack(side=BOTTOM,fill=X)
        scroll_y.pack(side=RIGHT,fill=Y)
        scroll_x.config(command=self.ispis.xview) 
        scroll_y.config(command=self.ispis.yview)
        self.ispis.heading("brojračuna",text="Broj računa")
        self.ispis.heading("idgosti",text="ID gosta")
        self.ispis.heading("trenutnostanje",text="Trenutno")
        self.ispis.heading("total",text="Total")
        self.ispis.heading("status",text="Status")
        self.ispis.heading("računDan",text="računDan")
        self.ispis['show']='headings' 
        self.ispis.column("brojračuna",width=100) 
        self.ispis.column("idgosti",width=100)
        self.ispis.column("trenutnostanje",width=100)
        self.ispis.column("total",width=100)
        self.ispis.column("status",width=120)
        self.ispis.column("računDan",width=100)
        self.ispis.bind("<ButtonRelease-1>",self.pokazivač)
        self.ispis.pack(fill=BOTH,expand=1)

        framePazar=LabelFrame(self.root,bd=2,relief=RIDGE,text="Pregledaj dane i pazar",font=("times new roman",12,"bold"),padx=2)
        framePazar.place(x=1470,y=210,width=440,height=300)

        dugmeOtvoriDan=Button(framePazar,text="Otvori Dan",command=self.otvoriDan, font=("arial",10,"bold"),bg="black",fg="gold",width=7)
        dugmeOtvoriDan.grid(row=0,column=4)

        dugmeZatvoriDan=Button(framePazar,text="Zatvori Dan",command=self.zatvoriDan, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        dugmeZatvoriDan.grid(row=1,column=4)

        dugmePazar=Button(framePazar,text="Upiši",command=self.upiširačun, font=("arial",10,"bold"),bg="black",fg="gold",width=7)
        dugmePazar.grid(row=2,column=4)

        dugmeDani=Button(framePazar,text="Dani",command=self.prikažiSveDane, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        dugmeDani.grid(row=3,column=4)

        dugmeDanas=Button(framePazar,text="Danas",command=self.prikažiDanas, font=("times new roman",10,"bold"),bg="black",fg="gold",width=7)
        dugmeDanas.grid(row=4,column=4)


        brojračunaLbl=Label(framePazar,text="Račun",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        brojračunaLbl.grid(row=0,column=0)

        brojračunaEntry=ttk.Entry(framePazar,textvariable=self.var_brojračuna, width=9,state="readonly")
        brojračunaEntry.grid(row=0,column=1)

        idgostLbl=Label(framePazar,text="IdGost",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        idgostLbl.grid(row=1,column=0)

        idgostEntry=ttk.Entry(framePazar,textvariable=self.var_idgosti, width=9)
        idgostEntry.grid(row=1,column=1)

        stanjeLbl=Label(framePazar,text="Stanje",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        stanjeLbl.grid(row=2,column=0)

        stanjeEntry=ttk.Entry(framePazar,textvariable=self.var_stanje, width=9)
        stanjeEntry.grid(row=2,column=1)

        totalLbl=Label(framePazar,text="Total",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        totalLbl.grid(row=3,column=0)

        totalEntry=ttk.Entry(framePazar,textvariable=self.var_total, width=9)
        totalEntry.grid(row=3,column=1)

        statusLbl=Label(framePazar,text="StatusR",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        statusLbl.grid(row=4,column=0)

        statusEntry=ttk.Entry(framePazar,textvariable=self.var_statusR, width=9)
        statusEntry.grid(row=4,column=1)

        računDanLbl=Label(framePazar,text="RDan",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        računDanLbl.grid(row=0,column=2)

        računDanEntry=ttk.Entry(framePazar,textvariable=self.var_računDan, width=9)
        računDanEntry.grid(row=0,column=3)

        danLbl=Label(framePazar,text="Dan",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        danLbl.grid(row=2,column=2)

        danEntry=ttk.Entry(framePazar,textvariable=self.var_dan, width=9)
        danEntry.grid(row=2,column=3)

        pazarLbl=Label(framePazar,text="Pazar", font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        pazarLbl.grid(row=3,column=2)

        pazarEntry=ttk.Entry(framePazar,textvariable=self.var_pazar, width=9)
        pazarEntry.grid(row=3,column=3)

        statusLbl=Label(framePazar,text="StatusD",font=("times new roman",12,"bold"),padx=2,pady=3,width=7)
        statusLbl.grid(row=4,column=2)

        statusEntry=ttk.Entry(framePazar,textvariable=self.var_statusD, width=9)
        statusEntry.grid(row=4,column=3)

        detaljiTabla2=Frame(framePazar)
        detaljiTabla2.place(x=0,y=150,width=370,height=130)

        scroll_x2 = Scrollbar(detaljiTabla2,orient=HORIZONTAL)
        scroll_y2 = Scrollbar(detaljiTabla2,orient=VERTICAL)
        self.ispis2=ttk.Treeview(detaljiTabla2,columns=("dan","kasa","status"),xscrollcommand=scroll_x2.set,yscrollcommand=scroll_y2.set)
        scroll_x2.pack(side=BOTTOM,fill=X)
        scroll_y2.pack(side=RIGHT,fill=Y)
        scroll_x2.config(command=self.ispis2.xview) 
        scroll_y2.config(command=self.ispis2.yview)
        self.ispis2.heading("dan",text="Dan")
        self.ispis2.heading("kasa",text="Kasa")
        self.ispis2.heading("status",text="Status")
        self.ispis2['show']='headings'  
        self.ispis2.column("dan",width=100)
        self.ispis2.column("kasa",width=100)
        self.ispis2.column("status",width=100)
        self.ispis2.bind("<ButtonRelease-1>",self.pokazivač2)
        self.ispis2.pack(fill=BOTH,expand=1)


        framePiće=LabelFrame(self.root,bd=2,relief=RIDGE,text="Pregled,porudžbina i naplata pića",font=("times new roman",12,"bold"),padx=2)
        framePiće.place(x=930,y=510,width=540,height=500)

        dugmePorudžbina=Button(framePiće,text="Poruči",command=self.porudžbina, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmePorudžbina.grid(row=0,column=0,pady=5)

        dugmeNovaTura=Button(framePiće,text="Nova tura",command=self.novaporudžbina, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmeNovaTura.grid(row=0,column=1)

        dugmeNaplata=Button(framePiće,text="Naplati",command=self.naplata, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmeNaplata.grid(row=0,column=2)

        dugmeObriši=Button(framePiće,text="Obriši",command=self.obriširačun, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmeObriši.grid(row=1,column=0,padx=10)

        dugmePoništi=Button(framePiće,text="Poništi",command=self.poništi, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmePoništi.grid(row=1,column=1,padx=10)

        dugmePiće=Button(framePiće,text="Piće/Hrana",command=self.prikažiArtikle, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmePiće.grid(row=1,column=2,padx=10)

        dugmeLimit=Button(framePiće,text="Limit",command=self.skidanjestavke, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        dugmeLimit.grid(row=1,column=3,padx=10)


        idnormativiLbl=Label(framePiće,text="ID stavke",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        idnormativiLbl.grid(row=2,column=0)

        idnormativiEntry=ttk.Entry(framePiće,textvariable=self.var_idnormativa, width=9)
        idnormativiEntry.grid(row=2,column=1)

        nazivLbl=Label(framePiće,text="Piće/Hrana",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        nazivLbl.grid(row=2,column=2)

        nazivEntry=ttk.Entry(framePiće,textvariable=self.var_nazivArtikla, width=14)
        nazivEntry.grid(row=2,column=3)

        cenaArtiklaLbl=Label(framePiće,text="Cena",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        cenaArtiklaLbl.grid(row=3,column=0)

        cenaArtiklaEntry=ttk.Entry(framePiće,textvariable=self.var_cenaArtikla, width=9)
        cenaArtiklaEntry.grid(row=3,column=1)

        količinaArtiklaLbl=Label(framePiće,text="Količina",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        količinaArtiklaLbl.grid(row=3,column=2)

        količinaArtiklaEntry=ttk.Entry(framePiće,textvariable=self.var_količinaArtikla, width=9)
        količinaArtiklaEntry.grid(row=3,column=3)

        idArtiklaLbl=Label(framePiće,text="ID artikla",font=("times new roman",12,"bold"),padx=2,pady=3,width=10)
        idArtiklaLbl.grid(row=4,column=0)

        idArtiklaEntry=ttk.Entry(framePiće,textvariable=self.var_idartikla, width=9)
        idArtiklaEntry.grid(row=4,column=1)

        btnTura=Button(framePiće,text="Tura",command=self.tura, font=("arial",12,"bold"),bg="black",fg="gold",width=8)
        btnTura.place(x=10,y=190,width=100,height=30)

        turaEntry=ttk.Entry(framePiće,textvariable=self.var_tura)
        turaEntry.place(x=120,y=190,width=100,height=30)

        detaljiTabla3=Frame(framePiće)
        detaljiTabla3.place(x=0,y=230,width=530,height=250)
        
        scroll_x3 = Scrollbar(detaljiTabla3,orient=HORIZONTAL)
        scroll_y3 = Scrollbar(detaljiTabla3,orient=VERTICAL)
        self.ispis3=ttk.Treeview(detaljiTabla3,columns=("idnormativi","nazivArtikla","cena","količina","idartikli"),xscrollcommand=scroll_x3.set,yscrollcommand=scroll_y3.set)
        scroll_x3.pack(side=BOTTOM,fill=X)
        scroll_y3.pack(side=RIGHT,fill=Y)
        scroll_x3.config(command=self.ispis3.xview) 
        scroll_y3.config(command=self.ispis3.yview)
        self.ispis3.heading("idnormativi",text="ID stavke")
        self.ispis3.heading("nazivArtikla",text="Naziv")
        self.ispis3.heading("cena",text="Cena")
        self.ispis3.heading("količina",text="Količina")
        self.ispis3.heading("idartikli",text="ID artikla")
        self.ispis3['show']='headings' 
        self.ispis3.column("idnormativi",width=100) 
        self.ispis3.column("nazivArtikla",width=100)
        self.ispis3.column("cena",width=100)
        self.ispis3.column("količina",width=100)
        self.ispis3.column("idartikli",width=100)
        self.ispis3.bind("<ButtonRelease-1>",self.pokazivač3)
        self.ispis3.pack(fill=BOTH,expand=1)


        dugmeProzor=Button(framePiće,text="Cene i nabavka",command=self.ceneNabavka, font=("arial",10,"bold"),bg="black",fg="gold",width=10)
        dugmeProzor.place(x=400,y=190,width=130,height=30)


        dugmeOff=Button(self.root,text="Ugasi konekciju",command=self.off, font=("arial",10,"bold"),bg="black",fg="gold",width=10)
        dugmeOff.place(x=1720,y=985,width=130,height=30)


    def prikažiSveRačune(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM restoranNaplata")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.ispis.delete(*self.ispis.get_children())
            for row in rows:
                self.ispis.insert('',END,values=row)
                con.commit()


    def pokazivač(self,event):
        cursor_row = self.ispis.focus()
        contents = self.ispis.item(cursor_row)
        row = contents['values']

        self.var_brojračuna.set(row[0])
        self.var_idgosti.set(row[1])
        self.var_stanje.set(row[2])
        self.var_total.set(row[3])
        self.var_statusR.set(row[4])
        self.var_računDan.set(row[5])

    def pronadjiračun(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM restoranNaplata WHERE "+str(self.var_pronadjiPo.get())+" LIKE binary '%"+self.var_pronadjiTekst.get()+"%'") 
        rows = cur.fetchall()
        if(len(rows)!=0):
            self.ispis.delete(*self.ispis.get_children())
            for i in rows: 
                self.ispis.insert('',END,values=i)
                con.commit()
        else:
            self.ispis.delete(*self.ispis.get_children()) 


    def prikažiSveDane(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM pazar")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.ispis2.delete(*self.ispis2.get_children())
            for row in rows:
                self.ispis2.insert('',END,values=row)
                con.commit()

    def prikažiDanas(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM pazar WHERE status='otvoren'")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.ispis2.delete(*self.ispis2.get_children())
            for row in rows:
                self.ispis2.insert('',END,values=row)
                con.commit()
    
    def pokazivač2(self,event):
        cursor_row = self.ispis2.focus()
        contents = self.ispis2.item(cursor_row)
        row = contents['values']

        self.var_dan.set(row[0])
        self.var_pazar.set(row[1])
        self.var_statusD.set(row[2])
        

    def otvoriDan(self):
        self.poništi()
        self.var_statusD.set("započni")
        if self.var_pazar.get()!=0 or self.var_statusD.get()!="započni":
            messagebox.showerror("Greška","Dan je već otvoren ili je prošao")
        else:
            self.var_statusD.set("otvoren")
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("INSERT INTO pazar(kasa,status) VALUES(%s,%s)",(self.var_pazar.get(),self.var_statusD.get(),))
            con.commit()
            messagebox.showinfo("Dobrodošli","Uspešno započet radni dan",parent=self.root)
            self.poništi()
            self.prikažiDanas()
            

    def zatvoriDan(self):
        if self.var_statusD.get()!="otvoren":
            messagebox.showerror("Greška","Dan je već prošao")
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("UPDATE pazar SET status='zatvoren' WHERE dan=%s",(self.var_dan.get(),))
            con.commit()
            messagebox.showinfo("Dovidjenja","Uspešno zatvoren radni dan",parent=self.root)
            self.poništi()
            self.prikažiSveDane()
            
    def prikažiArtikle(self):
        con=Konekcija.getInstance()
        cur=con.cursor()
        cur.execute("SELECT * FROM normativi")
        rows=cur.fetchall()
        if(len(rows)!=0):
            self.ispis3.delete(*self.ispis3.get_children())
            for row in rows:
                self.ispis3.insert('',END,values=row)
                con.commit()

    def pokazivač3(self,event):
        cursor_row = self.ispis3.focus()
        contents = self.ispis3.item(cursor_row)
        row = contents['values']
        if (f"{row[1]}")==(f"{self.var_espresso.get()}"):
            self.var_cena1.set(self.var_cena1.get()+row[2])
            self.var_količina1.set(self.var_količina1.get()+1)
            self.var_KN1.set(self.var_KN1.get()+row[3])
            self.var_idA1.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_aqua.get()}"):
            self.var_cena2.set(self.var_cena2.get()+row[2])
            self.var_količina2.set(self.var_količina2.get()+1)
            self.var_KN2.set(self.var_KN2.get()+row[3])
            self.var_idA2.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_knjaz.get()}"):
            self.var_cena3.set(self.var_cena3.get()+row[2])
            self.var_količina3.set(self.var_količina3.get()+1)
            self.var_KN3.set(self.var_KN3.get()+row[3])
            self.var_idA3.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_coca.get()}"):
            self.var_cena4.set(self.var_cena4.get()+row[2])
            self.var_količina4.set(self.var_količina4.get()+1)
            self.var_KN4.set(self.var_KN4.get()+row[3])
            self.var_idA4.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_next.get()}"):
            self.var_cena5.set(self.var_cena5.get()+row[2])
            self.var_količina5.set(self.var_količina5.get()+1)
            self.var_KN5.set(self.var_KN5.get()+row[3])
            self.var_idA5.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_limunada.get()}"):
            self.var_cena6.set(self.var_cena6.get()+row[2])
            self.var_količina6.set(self.var_količina6.get()+1)
            self.var_KN6.set(self.var_KN6.get()+row[3])
            self.var_idA6.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_cedjena.get()}"):
            self.var_cena7.set(self.var_cena7.get()+row[2])
            self.var_količina7.set(self.var_količina7.get()+1)
            self.var_KN7.set(self.var_KN7.get()+row[3])
            self.var_idA7.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_redbull.get()}"):
            self.var_cena8.set(self.var_cena8.get()+row[2])
            self.var_količina8.set(self.var_količina8.get()+1)
            self.var_KN8.set(self.var_KN8.get()+row[3])
            self.var_idA8.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_kozel.get()}"):
            self.var_cena9.set(self.var_cena9.get()+row[2])
            self.var_količina9.set(self.var_količina9.get()+1)
            self.var_KN9.set(self.var_KN9.get()+row[3])
            self.var_idA9.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_vino.get()}"):
            self.var_cena10.set(self.var_cena10.get()+row[2])
            self.var_količina10.set(self.var_količina10.get()+1)
            self.var_KN10.set(self.var_KN10.get()+row[3])
            self.var_idA10.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_whisky.get()}"):
            self.var_cena11.set(self.var_cena11.get()+row[2])
            self.var_količina11.set(self.var_količina11.get()+1)
            self.var_KN11.set(self.var_KN11.get()+row[3])
            self.var_idA11.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_cognac.get()}"):
            self.var_cena12.set(self.var_cena12.get()+row[2])
            self.var_količina12.set(self.var_količina12.get()+1)
            self.var_KN12.set(self.var_KN12.get()+row[3])
            self.var_idA12.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_martini.get()}"):
            self.var_cena13.set(self.var_cena13.get()+row[2])
            self.var_količina13.set(self.var_količina13.get()+1)
            self.var_KN13.set(self.var_KN13.get()+row[3])
            self.var_idA13.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_omlet.get()}"):
            self.var_cena14.set(self.var_cena14.get()+row[2])
            self.var_količina14.set(self.var_količina14.get()+1)
            self.var_KN14.set(self.var_KN14.get()+row[3])
            self.var_idA14.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pomfrit.get()}"):
            self.var_cena15.set(self.var_cena15.get()+row[2])
            self.var_količina15.set(self.var_količina15.get()+1)
            self.var_KN15.set(self.var_KN15.get()+row[3])
            self.var_idA15.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_meze.get()}"):
            self.var_cena16.set(self.var_cena16.get()+row[2])
            self.var_količina16.set(self.var_količina16.get()+1)
            self.var_KN16.set(self.var_KN16.get()+row[3])
            self.var_idA16.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_sendvič.get()}"):
            self.var_cena17.set(self.var_cena17.get()+row[2])
            self.var_količina17.set(self.var_količina17.get()+1)
            self.var_KN17.set(self.var_KN17.get()+row[3])
            self.var_idA17.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_čorba.get()}"):
            self.var_cena18.set(self.var_cena18.get()+row[2])
            self.var_količina18.set(self.var_količina18.get()+1)
            self.var_KN18.set(self.var_KN18.get()+row[3])
            self.var_idA18.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_paradajz.get()}"):
            self.var_cena19.set(self.var_cena19.get()+row[2])
            self.var_količina19.set(self.var_količina19.get()+1)
            self.var_KN19.set(self.var_KN19.get()+row[3])
            self.var_idA19.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_krastavac.get()}"):
            self.var_cena20.set(self.var_cena20.get()+row[2])
            self.var_količina20.set(self.var_količina20.get()+1)
            self.var_KN20.set(self.var_KN20.get()+row[3])
            self.var_idA20.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pečurke.get()}"):
            self.var_cena21.set(self.var_cena21.get()+row[2])
            self.var_količina21.set(self.var_količina21.get()+1)
            self.var_KN21.set(self.var_KN21.get()+row[3])
            self.var_idA21.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_špagete.get()}"):
            self.var_cena22.set(self.var_cena22.get()+row[2])
            self.var_količina22.set(self.var_količina22.get()+1)
            self.var_KN22.set(self.var_KN22.get()+row[3])
            self.var_idA22.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_bečka.get()}"):
            self.var_cena23.set(self.var_cena23.get()+row[2])
            self.var_količina23.set(self.var_količina23.get()+1)
            self.var_KN23.set(self.var_KN23.get()+row[3])
            self.var_idA23.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_medaljoni.get()}"):
            self.var_cena24.set(self.var_cena24.get()+row[2])
            self.var_količina24.set(self.var_količina24.get()+1)
            self.var_KN24.set(self.var_KN24.get()+row[3])
            self.var_idA24.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_pastrmka.get()}"):
            self.var_cena25.set(self.var_cena25.get()+row[2])
            self.var_količina25.set(self.var_količina25.get()+1)
            self.var_KN25.set(self.var_KN25.get()+row[3])
            self.var_idA25.set(row[4])
        elif (f"{row[1]}")==(f"{self.var_tuna.get()}"):
            self.var_cena26.set(self.var_cena26.get()+row[2])
            self.var_količina26.set(self.var_količina26.get()+1)
            self.var_KN26.set(self.var_KN26.get()+row[3])
            self.var_idA26.set(row[4])
        self.var_idnormativa.set(row[0])
        self.var_nazivArtikla.set(row[1])
        self.var_cenaArtikla.set(row[2])
        self.var_količinaArtikla.set(row[3])
        self.var_idartikla.set(row[4])


    def porudžbina(self):
        self.skidanjestavke()
        self.tura()
        self.var_stanje.set(self.var_tura.get())
        if self.var_idgosti.get()==0:
            messagebox.showerror("Greška", "Unesite id gosta kome je porudžbina namenjena!", parent=self.root)
        elif self.var_statusD.get()!="otvoren":
            messagebox.showerror("Greška", "Račun mora biti unet u tekući dan!", parent=self.root)
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("INSERT INTO restoranNaplata(idgosti,trenutnostanje,total,status,dan) VALUES(%s,%s,%s,%s,%s)",(self.var_idgosti.get(),self.var_stanje.get(),self.var_total.get(),self.var_statusR.get(),self.var_dan.get()))
            con.commit()
            messagebox.showinfo("OK","Uspešna porudžbina",parent=self.root)
            self.poništi()
            self.prikažiSveRačune()
            self.limit()
        
    def tura(self):
        sve=self.var_cena1.get()+self.var_cena2.get()+self.var_cena3.get()+self.var_cena4.get()+self.var_cena5.get()+self.var_cena6.get()+self.var_cena7.get()+self.var_cena8.get()+self.var_cena9.get()+self.var_cena10.get()+self.var_cena11.get()+self.var_cena12.get()+self.var_cena13.get()+self.var_cena14.get()+self.var_cena15.get()+self.var_cena16.get()+self.var_cena17.get()+self.var_cena18.get()+self.var_cena19.get()+self.var_cena20.get()+self.var_cena21.get()+self.var_cena22.get()+self.var_cena23.get()+self.var_cena24.get()+self.var_cena25.get()+self.var_cena26.get()
        self.var_tura.set(sve)

    def novaporudžbina(self):
        self.skidanjestavke()
        self.tura()
        if self.var_idgosti.get()==0:
            messagebox.showerror("Greška", "Unesite id gosta kome je porudžbina namenjena!", parent=self.root)
        elif self.var_stanje.get()==0 or self.var_statusR.get()!="otvoren" :
            messagebox.showerror("Greška", "Račun ne postoji ili je naplaćen!", parent=self.root)
        elif self.var_statusD.get()!="otvoren":
                messagebox.showerror("Greška", "Račun mora biti unet u tekući dan!", parent=self.root)
        else:
            self.var_stanje.set(self.var_stanje.get()+self.var_tura.get())
            try:
                con=Konekcija.getInstance()
                cursor=con.cursor()
                cursor.execute("UPDATE restoranNaplata SET trenutnostanje=%s  WHERE brojračuna=%s",(self.var_stanje.get(),self.var_brojračuna.get()))
                con.commit()
                messagebox.showinfo("OK","Uspešna porudžbina",parent=self.root)
                self.poništi()
                self.prikažiSveRačune()
            except Exception as es:
                messagebox.showwarning("Upozorenje",f"Nešto je pošlo loše:{es}",parent=self.root)
        

    def obriširačun(self):
        if self.var_total.get()!=0:
            messagebox.showerror("Greška", "Račun je već naplaćen", parent=self.root)
        else:
            obriši=messagebox.askyesno("Restoran","Da li zaista želite da obrišete ovaj račun?")
            if obriši>0:
                con=Konekcija.getInstance()
                cur=con.cursor()
                cur.execute("DELETE FROM restoranNaplata  WHERE brojračuna=%s",(self.var_brojračuna.get(),))
                con.commit()
                messagebox.showinfo("Uspešno obrisan račun!","Brisanje uspelo!")
                self.poništi()
                self.prikažiSveRačune()
        

    def naplata(self):
        if self.var_stanje.get()==0 or self.var_brojračuna.get()==0:
            messagebox.showerror("Greška","Ne postoji račun",parent=self.root)
        elif self.var_total.get()!=0:
            messagebox.showerror("Greška", "Račun je već naplaćen", parent=self.root)
        else:
            con=Konekcija.getInstance()
            cursor=con.cursor()
            cursor.execute("UPDATE restoranNaplata SET total=%s,status='naplaćen'  WHERE brojračuna=%s",(self.var_stanje.get()+self.var_total.get(),self.var_brojračuna.get()))
        if self.var_stanje.get()>5000:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+200  WHERE idgosti=%s",(self.var_idgosti.get(),))
                con.commit()
                messagebox.showinfo("Naplata", "Račun je uspešno naplaćen", parent=self.root)
                self.poništi()
                self.prikažiSveRačune()
        elif self.var_stanje.get()>3000 and self.var_stanje.get()<=5000:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+100 WHERE idgosti=%s",(self.var_idgosti.get(),))
                con.commit()
                messagebox.showinfo("Naplata", "Račun je uspešno naplaćen", parent=self.root)
                self.poništi()
                self.prikažiSveRačune()
        else:
                cursor.execute("UPDATE gosti SET bodovi=bodovi+50  WHERE idgosti=%s",(self.var_idgosti.get(),))
                con.commit()
                messagebox.showinfo("Naplata", "Račun je uspešno naplaćen", parent=self.root)
                self.poništi()
                self.prikažiSveRačune()
            
            

    def upiširačun(self):
        if self.var_statusD.get()!="otvoren" :
            messagebox.showerror("Greška", "Ovaj dan je završen,izaberite tekući dan!", parent=self.root)
        elif self.var_računDan.get()!=self.var_dan.get():
            messagebox.showerror("Greška", "Ovaj račun nije otvoren ovog dana!!", parent=self.root)
        else:
            if self.var_statusR.get()=="naplaćen":
                con=Konekcija.getInstance()
                cur=con.cursor()
                cur.execute("UPDATE pazar SET kasa=%s WHERE dan=%s",(self.var_pazar.get()+self.var_total.get(),self.var_dan.get(),))
                cur.execute("UPDATE restoranNaplata SET status='upisan u kasu' WHERE brojračuna=%s",(self.var_brojračuna.get(),))
                con.commit()
                messagebox.showinfo("OK","Uspešno uvećan pazar",parent=self.root)
                self.poništi()
                self.prikažiSveRačune()
                self.prikažiDanas()
            elif self.var_statusR.get()=="upisan u kasu":
                messagebox.showerror("Greška", "Račun je već upisan u kasu", parent=self.root)
            else:
                messagebox.showerror("Greška", "Račun nije naplaćen", parent=self.root)

    def poništi(self):
        self.var_količina1.set(0)
        self.var_količina2.set(0)
        self.var_količina3.set(0)
        self.var_količina4.set(0)
        self.var_količina5.set(0)
        self.var_količina6.set(0)
        self.var_količina7.set(0)
        self.var_količina8.set(0)
        self.var_količina9.set(0)
        self.var_količina10.set(0)
        self.var_količina11.set(0)
        self.var_količina12.set(0)
        self.var_količina13.set(0)
        self.var_količina14.set(0)
        self.var_količina15.set(0)
        self.var_količina16.set(0)
        self.var_količina17.set(0)
        self.var_količina18.set(0)
        self.var_količina19.set(0)
        self.var_količina20.set(0)
        self.var_količina21.set(0)
        self.var_količina22.set(0)
        self.var_količina23.set(0)
        self.var_količina24.set(0)
        self.var_količina25.set(0)
        self.var_količina26.set(0)
        self.var_cena1.set(0)
        self.var_cena2.set(0)
        self.var_cena3.set(0)
        self.var_cena4.set(0)
        self.var_cena5.set(0)
        self.var_cena6.set(0)
        self.var_cena7.set(0)
        self.var_cena8.set(0)
        self.var_cena9.set(0)
        self.var_cena10.set(0)
        self.var_cena11.set(0)
        self.var_cena12.set(0)
        self.var_cena13.set(0)
        self.var_cena14.set(0)
        self.var_cena15.set(0)
        self.var_cena16.set(0)
        self.var_cena17.set(0)
        self.var_cena18.set(0)
        self.var_cena19.set(0)
        self.var_cena20.set(0)
        self.var_cena21.set(0)
        self.var_cena22.set(0)
        self.var_cena23.set(0)
        self.var_cena24.set(0)
        self.var_cena25.set(0)
        self.var_cena26.set(0)
        self.var_idA1.set(0)
        self.var_idA2.set(0)
        self.var_idA3.set(0)
        self.var_idA4.set(0)
        self.var_idA5.set(0)
        self.var_idA6.set(0)
        self.var_idA7.set(0)
        self.var_idA8.set(0)
        self.var_idA9.set(0)
        self.var_idA10.set(0)
        self.var_idA11.set(0)
        self.var_idA12.set(0)
        self.var_idA13.set(0)
        self.var_idA14.set(0)
        self.var_idA15.set(0)
        self.var_idA16.set(0)
        self.var_idA17.set(0)
        self.var_idA18.set(0)
        self.var_idA19.set(0)
        self.var_idA20.set(0)
        self.var_idA21.set(0)
        self.var_idA22.set(0)
        self.var_idA23.set(0)
        self.var_idA24.set(0)
        self.var_idA25.set(0)
        self.var_idA26.set(0)
        self.var_KN1.set(0)
        self.var_KN2.set(0)
        self.var_KN3.set(0)
        self.var_KN4.set(0)
        self.var_KN5.set(0)
        self.var_KN6.set(0)
        self.var_KN7.set(0)
        self.var_KN8.set(0)
        self.var_KN9.set(0)
        self.var_KN10.set(0)
        self.var_KN11.set(0)
        self.var_KN12.set(0)
        self.var_KN13.set(0)
        self.var_KN14.set(0)
        self.var_KN15.set(0)
        self.var_KN16.set(0)
        self.var_KN17.set(0)
        self.var_KN18.set(0)
        self.var_KN19.set(0)
        self.var_KN20.set(0)
        self.var_KN21.set(0)
        self.var_KN22.set(0)
        self.var_KN23.set(0)
        self.var_KN24.set(0)
        self.var_KN25.set(0)
        self.var_KN26.set(0)

        self.var_brojračuna.set(0)
        self.var_idgosti.set(0)
        self.var_stanje.set(0)
        self.var_total.set(0)
        self.var_statusR.set("otvoren")
        self.var_računDan.set(0)
        self.var_pronadjiPo.set("")
        self.var_pronadjiTekst.set("")
        if self.var_statusD.get()!="otvoren":
            self.var_dan.set("")
            self.var_pazar.set(0)
            self.var_statusD.set("")
        self.var_idnormativa.set(0)
        self.var_nazivArtikla.set("")
        self.var_cenaArtikla.set(0)
        self.var_količinaArtikla.set(0)
        self.var_idartikla.set(0)
        self.var_tura.set(0)
        self.ispis.delete(*self.ispis.get_children())
        self.ispis2.delete(*self.ispis2.get_children())
        self.ispis3.delete(*self.ispis3.get_children())
        self.prikažiDanas()


    def x3(self):
        self.x=[]
        self.x.extend((self.var_KN1.get(),self.var_KN2.get(),self.var_KN3.get(),self.var_KN4.get(),self.var_KN5.get(),self.var_KN6.get(),self.var_KN7.get(),self.var_KN8.get(),self.var_KN9.get(),self.var_KN10.get(),self.var_KN11.get(),self.var_KN12.get(),self.var_KN13.get(),self.var_KN14.get(),self.var_KN15.get(),self.var_KN16.get(),self.var_KN17.get(),self.var_KN18.get(),self.var_KN19.get(),self.var_KN20.get(),self.var_KN21.get(),self.var_KN22.get(),self.var_KN23.get(),self.var_KN24.get(),self.var_KN25.get(),self.var_KN26.get()))
        self.y=[]
        self.y.extend((self.var_količina1.get(),self.var_količina2.get(),self.var_količina3.get(),self.var_količina4.get(),self.var_količina5.get(),self.var_količina6.get(),self.var_količina7.get(),self.var_količina8.get(),self.var_količina9.get(),self.var_količina10.get(),self.var_količina11.get(),self.var_količina12.get(),self.var_količina13.get(),self.var_količina14.get(),self.var_količina15.get(),self.var_količina16.get(),self.var_količina17.get(),self.var_količina18.get(),self.var_količina19.get(),self.var_količina20.get(),self.var_količina21.get(),self.var_količina22.get(),self.var_količina23.get(),self.var_količina24.get(),self.var_količina25.get(),self.var_količina26.get()))
        self.z=[]
        self.z.extend((self.var_idA1.get(),self.var_idA2.get(),self.var_idA3.get(),self.var_idA4.get(),self.var_idA5.get(),self.var_idA6.get(),self.var_idA7.get(),self.var_idA8.get(),self.var_idA9.get(),self.var_idA10.get(),self.var_idA11.get(),self.var_idA12.get(),self.var_idA13.get(),self.var_idA14.get(),self.var_idA15.get(),self.var_idA16.get(),self.var_idA17.get(),self.var_idA18.get(),self.var_idA19.get(),self.var_idA20.get(),self.var_idA21.get(),self.var_idA22.get(),self.var_idA23.get(),self.var_idA24.get(),self.var_idA25.get(),self.var_idA26.get()))
    def skidanjestavke(self):
        self.x3()
        con=Konekcija.getInstance()
        cursor=con.cursor()
        sql=("UPDATE artikli SET stanjeKgLiKom=stanjeKgLiKom-%s WHERE idartikli=%s")
        for i in range(len(self.x)):
            if i==0:
                value=(self.x[i]*0.01,self.z[i])
                cursor.execute(sql,value)
            elif i==1 or i==2 or i==3 or i==4 or i==7:
                value=(self.x[i]*0.25,self.z[i])
                cursor.execute(sql,value)
            elif i==5:
                value=(self.x[i]*0.2,self.z[i])
                cursor.execute(sql,value)
            elif i==6:
                value=(self.x[i]*0.3,self.z[i])
                cursor.execute(sql,value)
            elif i==8:
                value=(self.x[i]*0.5,self.z[i])
                cursor.execute(sql,value)
            elif i==9:
                value=(self.x[i]*0.15,self.z[i])
                cursor.execute(sql,value)
            elif i==10 or i==11 or i==12:
                value=(self.x[i]*0.03,self.z[i])
                cursor.execute(sql,value)
            elif i==14 or i==16 or i==17:
                value=(self.x[i]*0.2,self.z[i])
                cursor.execute(sql,value)
            elif i==13:
                value=(self.x[i],self.z[i])
                cursor.execute(sql,value)
            else:
                value=(self.x[i]*0.4,self.z[i])
                cursor.execute(sql,value)
        con.commit()

    def limit(self):
        con=Konekcija.getInstance()
        cursor=con.cursor()
        cursor.execute("SELECT * FROM artikli")
        kolone=cursor.fetchall()
        for kolona in kolone :
            if (kolona[2]<kolona[3]):
                messagebox.showinfo("Upozorenje", "Limit je probijen,potrebna je nabavka!!!", parent=self.root)
                messagebox.showinfo("Upozorenje", "Nabavka: " +kolona[1], parent=self.root)
                con.commit()

    def off(self):
        con=Konekcija.getInstance()
        messagebox.showinfo("off","Odjavljivanje uspelo!")
        con.close()

    def datum(self):
        now = strftime("%Y-%m-%d %H:%M:%S")
        self.lbl.config(text = now)
        self.lbl.after(1000, self.datum)
    
    def ceneNabavka(self):
        self.new_window=Toplevel(self.root)
        self.app=CeneNabavka(self.new_window)

    def zatvoriProzor(self):
            response=messagebox.askyesno('Izlaz','Da li ste sigurni da želite da izadjete?',parent=self.root)
            if response:
                self.root.destroy()

'''root=Tk()
object=Restoran(root)
mainloop()'''  